name: Build sources
on:
  push:
    branches:
      - main
    paths:
      - "sources/**"
      - "templates/**"
      - ".github/workflows/build.yaml"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  build:
    env:
      RUSTC_WRAPPER: sccache
      SCCACHE_CACHE_SIZE: 2G
      SCCACHE_VERSION: 0.3.0
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: google/wireit@setup-github-actions-caching/v1
      - name: Cache rust stuff
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry/index
            ~/.cargo/registry/cache
            ~/.cargo/git/db
            ~/.cargo/bin
            sources/**/target/
          key: ${{ runner.os }}-cargo3-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo3-
      - name: sccache
        uses: actions/cache@v4
        with:
          path: ~/.cache/sccache
          key: ${{ runner.os }}-sccache-${{ github.sha }}
          restore-keys: ${{ runner.os }}-sccache-
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          target: wasm32-unknown-unknown
      - name: Install build dependencies
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          sudo apt-get update
          sudo apt-get install -y sccache
          if ! command -v aidoku >/dev/null 2>&1; then
            cargo install --git https://github.com/Aidoku/aidoku-rs --branch next aidoku-cli
          fi
      - name: Build sources
        run: |
          for src in ./sources/*; do
            (
              cd "$src"
              aidoku package
            )
          done
      - name: Build source list
        run: |
          aidoku build sources/*/package.aix --name "Aidoku Community Sources"
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4.7.2
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          branch: gh-pages
          folder: public
          git-config-name: GitHub Actions
          git-config-email: github-actions[bot]@users.noreply.github.com
          commit-message: Update source list
          single-commit: true
      - name: Uploading packages as artifact
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: packages
          path: public/sources/*.aix
          if-no-files-found: ignore
      - name: Uploading gh-pages deployment as artifact
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: gh-pages
          path: public
          if-no-files-found: ignore
